[package]
name = "my_proc_macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1", features = ["extra-traits"] }
proc-macro2 = "1"
quote = "1"
darling = "0.14"

[workspace]